//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES_classification.ServiceReferenceForExpertSystem {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceForExpertSystem.WebServiceForExpertSystemSoap")]
    public interface WebServiceForExpertSystemSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dbwGetDataSetForBayesSystem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet dbwGetDataSetForBayesSystem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dbwAddNewQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string dbwAddNewQuestion(string questionString, int functionalAreaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceForExpertSystemSoapChannel : ES_classification.ServiceReferenceForExpertSystem.WebServiceForExpertSystemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceForExpertSystemSoapClient : System.ServiceModel.ClientBase<ES_classification.ServiceReferenceForExpertSystem.WebServiceForExpertSystemSoap>, ES_classification.ServiceReferenceForExpertSystem.WebServiceForExpertSystemSoap {
        
        public WebServiceForExpertSystemSoapClient() {
        }
        
        public WebServiceForExpertSystemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceForExpertSystemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceForExpertSystemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceForExpertSystemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet dbwGetDataSetForBayesSystem() {
            return base.Channel.dbwGetDataSetForBayesSystem();
        }
        
        public string dbwAddNewQuestion(string questionString, int functionalAreaId) {
            return base.Channel.dbwAddNewQuestion(questionString, functionalAreaId);
        }
    }
}
